name: demo github action

on:
  push:
    branches:
      - devops-simple-node1
  pull_request:
    branches:
      - devops-simple-node1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Listar archivos
        run: ls -a
