name: demo github action

on:
  push:
    branches:
      - devops-simple-node1
  pull_request:
    branches:
      - devops-simple-node1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 21

      - name: instalar dependencias
        run: npm install
      - name: instalar test
         run: npm run test
